kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nginx-fallback
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      namespace: nginx-fallback
      name: 'nginx-fallback:0.0.1'
  source:
    type: Dockerfile
    dockerfile: >-
        FROM nginx:stable

        # support running as arbitrary user which belogs to the root group
        RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx
        # users are not allowed to listen on priviliged ports
        RUN sed -i.bak 's/listen\(.*\)80;/listen 8080;/' /etc/nginx/conf.d/default.conf
        EXPOSE 8080
        # comment user directive as master process is run as user in OpenShift anyhow
        RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'nginx:stable'
